apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-be-deployment
  namespace: taskflow
  labels:
    app: taskflow-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-be
  template:
    metadata:
      labels:
        app: taskflow-be
    spec:
      containers:
      - name: taskflow-be
        image: souravsahoo08/microservice-k8-backend:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      envfrom:
      - configmapRef:
          name: taskflow-configmap
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: taskflow-secret
            key: DB_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: taskflow-be-service
spec:
  selector:
    app: taskflow-be
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    