apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-be-deployment
  labels:
    app: taskflow-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-be
  template:
    metadata:
      labels:
        app: taskflow-be
    spec:
      containers:
      - name: taskflow-be
        image: souravsahoo08/microservice-k8-backend:v1.0
        ports:
        - containerPort: 3000
